### ISSUE TITLE
mining-dutch

### ISSUE THREAD

**Issue by Twente-Mining** [yuzi-co/Megaminer#2]
hey Yuzi-co,

can you help me to add mining-dutch.nl to megaminer? 
I haven't been able to do so myself. 
Although I have been able to add it to be manually selectable no miner is being started. 

Thanks in advance =)

**Comment by yuzi-co** [comment]
I'll take a look at it

**Comment by Twente-Mining** [comment]
thanks =)

**Comment by yuzi-co** [comment]
Added

**Comment by Twente-Mining** [comment]
thanks =D

**Comment by Twente-Mining** [comment]
could you also make it possible that it is able to run on automatic switching mode?
If not, what should the pool change in its api to make it work?

**Comment by yuzi-co** [comment]
They don't provide profitability API
Right now, you can include it in WhatToMine virtual pool to add the few coins that have profitability available

**Comment by bagaut** [comment]
may be it will help https://www.mining-dutch.nl/?page=apidoc its api doc from miningdutch
